@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBZG1pbiIsImNyZWF0ZWRBdCI6MTYwODc2NzY1MiwiZXhwaXJlZEF0IjoxNjA4ODU0MDUyLCJpYXQiOjE2MDg3Njc2NTJ9.9FXk4wNrMV9558FuxpNSd1fPUDe27eox8vmJ83jVPfo

###
GET {{url}}/api/usuarios/getToken

### API USUARIOS
GET {{url}}/api/usuarios
user-token: {{token}}
###
POST {{url}}/api/usuarios
user-token: {{token}}
###
PUT {{url}}/api/usuarios
###
DELETE {{url}}/api/usuarios
###
### API ANUNCIOS
GET {{url}}/api/anuncios
###
POST {{url}}/api/anuncios
###
PUT {{url}}/api/anuncios
###
DELETE {{url}}/api/anuncios
###
### API NOTICIAS
GET {{url}}/api/noticias
###
POST {{url}}/api/noticias
###
PUT {{url}}/api/noticias
###
DELETE {{url}}/api/noticias
###
### API MOTOCICLETAS
GET {{url}}/api/motos
###
POST {{url}}/api/motos
Content-Type: application/json

{
    "tipo": "asdf"
}
###
PUT {{url}}/api/motos
###
DELETE {{url}}/api/motos


### registrar usuario

POST {{url}}/api/usuarios/registro
Content-Type: application/json

{
    "username": "deivit",
    "password": "12345",
    "email": "deivit@deivit.es"
}

### UPLOAD IMAGEN
POST {{url}}/api/anuncios/upload
Content-Type: multipart/form-data

{

}

### login usuario

POST {{url}}/api/usuarios/login
Content-Type: application/json

{
    "email": "deivit@deivit.es",
    "password": "12345"
}


###
GET {{url}}/api/anuncios/1
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQWRtaW4iLCJjcmVhdGVkQXQiOjE1OTMzODU1OTgsImV4cGlyZWRBdCI6MTU5MzM4OTE5OCwiaWF0IjoxNTkzMzg1NTk4fQ.Dv0D1Q6VuRyZvX3UARSLFNxbJhQoj3IXWnEFhV3AXxY

###
PUT {{url}}/api/anuncios/1
Content-Type: application/json
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQWRtaW4iLCJjcmVhdGVkQXQiOjE1OTMzODU1OTgsImV4cGlyZWRBdCI6MTU5MzM4OTE5OCwiaWF0IjoxNTkzMzg1NTk4fQ.Dv0D1Q6VuRyZvX3UARSLFNxbJhQoj3IXWnEFhV3AXxY

{
  "titulo": "vendo",
  "descripcion": "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",
  "km": 7500,
  "year": 1995,
  "provincia": "Denia",
  "poblacion": "Alicante",
  "itv": 1,
  "homologacion": 1,
  "fecha_publicacion": "2020-06-28T23:32:28.000Z",
  "precio": 7300,
  "marca": "Aprilia",
  "modelo": "Shiver",
  "usuarios_id": 23,
  "imagen_id": null,
  "categoria": "bobber"
}

###
GET {{url}}/api/perfil

###
GET {{url}}/api/anuncios/getbycategoria/bobber
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQWRtaW4iLCJjcmVhdGVkQXQiOjE1OTMzODU1OTgsImV4cGlyZWRBdCI6MTU5MzM4OTE5OCwiaWF0IjoxNTkzMzg1NTk4fQ.Dv0D1Q6VuRyZvX3UARSLFNxbJhQoj3IXWnEFhV3AXxY

###
GET {{url}}/api/motos


###
POST http://pikukoiptv.zapto.org:25500/api.php
###
GET  {{url}}/api/tutoriales
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQ29uc3RydWN0b3IiLCJjcmVhdGVkQXQiOjE1OTMzMDczNDEsImV4cGlyZWRBdCI6MTU5MzMxMDk0MSwiaWF0IjoxNTkzMzA3MzQxfQ.W87vAxIqMfF_X7GMzPZvAadVdtXDJr_5BgxqfcLv5WY

###
PUT {{url}}/api/usuarios/52
Content-Type: application/json
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQ29uc3RydWN0b3IiLCJjcmVhdGVkQXQiOjE1OTMzMDczNDEsImV4cGlyZWRBdCI6MTU5MzMxMDk0MSwiaWF0IjoxNTkzMzA3MzQxfQ.W87vAxIqMfF_X7GMzPZvAadVdtXDJr_5BgxqfcLv5WY

{
    "username": "pepito",
    "email": "deivit@deivit.es",
    "password": "12345"
}

###
PUT {{url}}/api/anuncios/1
Content-Type: application/json
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQ29uc3RydWN0b3IiLCJjcmVhdGVkQXQiOjE1OTMzNjAyMjYsImV4cGlyZWRBdCI6MTU5MzM2MzgyNiwiaWF0IjoxNTkzMzYwMjI2fQ.mys_tbk5HYwV_8I3J4ZtRLS0y5KvtqyD-onjn_pXNOA

  {
    "titulo": "vendo moto",
    "descripcion": "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",
    "km": 7500,
    "year": 1995,
    "provincia": "Denia",
    "poblacion": "Alicante",
    "itv": 1,
    "homologacion": 1,
    "fecha_publicacion": "2020-06-22T13:25:05.000Z",
    "precio": 7300,
    "marca": "Aprilia",
    "modelo": "Shiver",
    "usuarios_id": null,
    "imagen_id": ""
  }

###
PUT {{url}}/api/tutoriales/1
Content-Type: application/json
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQ29uc3RydWN0b3IiLCJjcmVhdGVkQXQiOjE1OTMzNjM5OTUsImV4cGlyZWRBdCI6MTU5MzM2NzU5NSwiaWF0IjoxNTkzMzYzOTk1fQ.lctmGNgOF_VWL__dClEnFBvT05WSD0rLVUr1skOnobI

{
    "titulo": "trucutru",
    "descripcion": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur perspiciatis, aperiam, magnam suscipit ut omnis id itaque rerum maxime perferendis laborum cum quasi modi sed ad praesentium. Blanditiis ipsum necessitatibus atque repellat, pariatur ab delectus officiis iure maxime iste nisi!c ",
    "autor": "Perico Palotes",
    "categoria": "electricidad",
    "url_video": "SAASD",
    "fecha_publicacion": "2020-06-25T09:16:59.000Z",
    "usuarios_id": null
  }

###
GET http://mypanel.sytes.net:3000/api/usuarios/getToken

###

GET http://mypanel.sytes.net:3000/api/usuarios
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBZG1pbiIsImNyZWF0ZWRBdCI6MTYwMTAxOTQ2MSwiZXhwaXJlZEF0IjoxNjAxMDIzMDYxLCJpYXQiOjE2MDEwMTk0NjF9.3f43h6WZl7jQqZ3McGP1WMCg2kjqBp1pXvrULslDl80

###
GET http://mypanel.sytes.net:3555/editor3
Authorization: Basic cm9vdDoxeTIrUg==

###
GET {{url}}/api/usuarios/getToken

###
GET {{url}}/api/usuarios


###
PUT {{url}}/api/usuarios/1
Content-Type: application/json
user-token: {{token}}

{
  "email": "admin@admin.com"
}

###
POST {{url}}/api/usuarios
Content-Type: application/json
user-token: {{token}}

{
  "username": "deivit",
  "email": "admin@olddonkeygarage.com",
  "password": "123"
}
