### API USUARIOS
GET http://localhost:3000/api/usuarios
UserToken: 
###
POST http://localhost:3000/api/usuarios
###
PUT http://localhost:3000/api/usuarios
###
DELETE http://localhost:3000/api/usuarios
###
### API ANUNCIOS
GET http://localhost:3000/api/anuncios
###
POST http://localhost:3000/api/anuncios
###
PUT http://localhost:3000/api/anuncios
###
DELETE http://localhost:3000/api/anuncios
###
### API NOTICIAS
GET http://localhost:3000/api/noticias
###
POST http://localhost:3000/api/noticias
###
PUT http://localhost:3000/api/noticias
###
DELETE http://localhost:3000/api/noticias
###
### API MOTOCICLETAS
GET http://localhost:3000/api/motos
###
POST http://localhost:3000/api/motos
Content-Type: application/json

{
    "tipo": "asdf"
}
###
PUT http://localhost:3000/api/motos
###
DELETE http://localhost:3000/api/motos


### registrar usuario

POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "username": "deivit",
    "password": "12345",
    "email": "deivit@deivit.es"
}

### UPLOAD IMAGEN
POST http://localhost:3000/api/anuncios/upload
Content-Type: multipart/form-data

{
  
}

### login usuario

POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email": "deivit@deivit.es",
    "password": "12345"
}


###
GET http://localhost:3000/api/anuncios/1
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQWRtaW4iLCJjcmVhdGVkQXQiOjE1OTMzODU1OTgsImV4cGlyZWRBdCI6MTU5MzM4OTE5OCwiaWF0IjoxNTkzMzg1NTk4fQ.Dv0D1Q6VuRyZvX3UARSLFNxbJhQoj3IXWnEFhV3AXxY

###
PUT http://localhost:3000/api/anuncios/1
Content-Type: application/json
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQWRtaW4iLCJjcmVhdGVkQXQiOjE1OTMzODU1OTgsImV4cGlyZWRBdCI6MTU5MzM4OTE5OCwiaWF0IjoxNTkzMzg1NTk4fQ.Dv0D1Q6VuRyZvX3UARSLFNxbJhQoj3IXWnEFhV3AXxY

{
  "titulo": "vendo",
  "descripcion": "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",
  "km": 7500,
  "year": 1995,
  "provincia": "Denia",
  "poblacion": "Alicante",
  "itv": 1,
  "homologacion": 1,
  "fecha_publicacion": "2020-06-28T23:32:28.000Z",
  "precio": 7300,
  "marca": "Aprilia",
  "modelo": "Shiver",
  "usuarios_id": 23,
  "imagen_id": null,
  "categoria": "bobber"
}

###
GET http://localhost:3000/api/perfil

###
GET http://localhost:3000/api/anuncios/getbycategoria/bobber
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQWRtaW4iLCJjcmVhdGVkQXQiOjE1OTMzODU1OTgsImV4cGlyZWRBdCI6MTU5MzM4OTE5OCwiaWF0IjoxNTkzMzg1NTk4fQ.Dv0D1Q6VuRyZvX3UARSLFNxbJhQoj3IXWnEFhV3AXxY

###
GET http://localhost:3000/api/motos


###
POST http://pikukoiptv.zapto.org:25500/api.php
###
GET  http://localhost:3000/api/tutoriales
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQ29uc3RydWN0b3IiLCJjcmVhdGVkQXQiOjE1OTMzMDczNDEsImV4cGlyZWRBdCI6MTU5MzMxMDk0MSwiaWF0IjoxNTkzMzA3MzQxfQ.W87vAxIqMfF_X7GMzPZvAadVdtXDJr_5BgxqfcLv5WY

###
PUT http://localhost:3000/api/usuarios/52
Content-Type: application/json
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQ29uc3RydWN0b3IiLCJjcmVhdGVkQXQiOjE1OTMzMDczNDEsImV4cGlyZWRBdCI6MTU5MzMxMDk0MSwiaWF0IjoxNTkzMzA3MzQxfQ.W87vAxIqMfF_X7GMzPZvAadVdtXDJr_5BgxqfcLv5WY

{   
    "username": "pepito",
    "email": "deivit@deivit.es",
    "password": "12345"
}

###
PUT http://localhost:3000/api/anuncios/1
Content-Type: application/json
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQ29uc3RydWN0b3IiLCJjcmVhdGVkQXQiOjE1OTMzNjAyMjYsImV4cGlyZWRBdCI6MTU5MzM2MzgyNiwiaWF0IjoxNTkzMzYwMjI2fQ.mys_tbk5HYwV_8I3J4ZtRLS0y5KvtqyD-onjn_pXNOA

  {
    "titulo": "vendo moto",
    "descripcion": "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.",
    "km": 7500,
    "year": 1995,
    "provincia": "Denia",
    "poblacion": "Alicante",
    "itv": 1,
    "homologacion": 1,
    "fecha_publicacion": "2020-06-22T13:25:05.000Z",
    "precio": 7300,
    "marca": "Aprilia",
    "modelo": "Shiver",
    "usuarios_id": null,
    "imagen_id": ""
  }

### 
PUT http://localhost:3000/api/tutoriales/1
Content-Type: application/json
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJyb2xlIjoiQ29uc3RydWN0b3IiLCJjcmVhdGVkQXQiOjE1OTMzNjM5OTUsImV4cGlyZWRBdCI6MTU5MzM2NzU5NSwiaWF0IjoxNTkzMzYzOTk1fQ.lctmGNgOF_VWL__dClEnFBvT05WSD0rLVUr1skOnobI

{
    "titulo": "trucutru",
    "descripcion": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur perspiciatis, aperiam, magnam suscipit ut omnis id itaque rerum maxime perferendis laborum cum quasi modi sed ad praesentium. Blanditiis ipsum necessitatibus atque repellat, pariatur ab delectus officiis iure maxime iste nisi!c ",
    "autor": "Perico Palotes",
    "categoria": "electricidad",
    "url_video": "SAASD",
    "fecha_publicacion": "2020-06-25T09:16:59.000Z",
    "usuarios_id": null
  }

###
GET http://mypanel.sytes.net:3000/api/usuarios/getToken

###

GET http://mypanel.sytes.net:3000/api/usuarios
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBZG1pbiIsImNyZWF0ZWRBdCI6MTYwMTAxOTQ2MSwiZXhwaXJlZEF0IjoxNjAxMDIzMDYxLCJpYXQiOjE2MDEwMTk0NjF9.3f43h6WZl7jQqZ3McGP1WMCg2kjqBp1pXvrULslDl80